# Generated by Django 3.2.7 on 2021-11-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klamotten', '0002_artikelchosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikelchosen',
            name='Artikelnummer',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
